name: holamundoworkflowPrueba1
on: 
  push:
    branches:
      - "main"

jobs:
  holamundojob:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir
        run: echo "hola mundo, step imprimir"
      - name: clone repo
        run: git clone https://${{github.actor}}:${{github.token}}@github.com/mariagrisales/workshop_gitAction.git
      - name: view
        run: ls -lha

  actioncheckout:
    needs: [holamundojob]    
    runs-on: ubuntu-latest
    steps:
      - name: ejecutar github action checkout
        uses: actions/checkout@v3
      - name: view
        run: ls -lha
      