name: holamundoworkflowPrueba2
on: 
  push:
    branches:
      - "main"

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: ejecutar github action checkout en prueba 2
        uses: actions/checkout@v3
#https://github.com/marketplace/actions/setup-go-environment
      - name: prepare environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.1'
      - name: print go-version
        run: go version
      - name: Build
        run: go build -v .
      - name: unit test
        run: go test -v .